Repository jigar288/CloudVOD, pull requests merged in 2021-04, with the labels that each got.

#206 Updated db api logic v3
  api/package-lock.json
  api/src/app.ts
  api/src/controllers/Auth.ts
  api/src/controllers/VideoController.ts
  api/src/controllers/index.ts
  api/src/data/MediaClient.ts
  api/src/data/VideoDatabaseClient.ts
  api/src/types/User.d.ts
  api/src/types/Video.d.ts
  sql-code/sql-functions-and-procedures/video/create_initial_video_entry.sql
  sql-code/sql-functions-and-procedures/video/update_streaming_url_by_asset.sql
  sql-code/sql-functions-and-procedures/video/update_video_metadata.sql
Labels: database, enhancement

#215 update express open id to 2.3.1
  api/package-lock.json
  api/package.json
Labels: dependencies

#158 WIP: UI
  api/package.json
  client/.env.defaults
  client/.env.example
  client/babel.config.js
  client/index.ejs
  client/jest.config.ts
  client/package-lock.json
  client/package.json
  client/src/components/App/index.tsx
  client/src/components/Navbar/index.tsx
  client/src/components/VideoCard/index.tsx
  client/src/components/VideoPlayer/index.tsx
  client/src/components/VideoView/index.tsx
  client/src/development/data.ts
  client/src/index.test.tsx
  client/src/index.tsx
  client/src/pages/AboutPage.tsx
  client/src/pages/UploadPage.tsx
  client/src/pages/VideoPage.tsx
  client/src/pages/VideosPage.tsx
  client/src/pages/index.tsx
  client/src/redux/index.ts
  client/src/state/data.ts
  client/src/state/error.ts
  client/src/state/index.ts
  client/src/state/loading.ts
  client/src/state/sanity.ts
  client/src/state/store.ts
  client/src/state/user.ts
  client/src/tests/test.setup.ts
  client/src/types/Category.d.ts
  client/src/types/Video.d.ts
  client/src/types/components/App.d.ts
  client/src/types/components/Navbar.d.ts
  client/src/types/index.d.ts
  client/src/utilities/index.ts
  client/src/utilities/paths.tsx
  client/src/utilities/routes.tsx
  client/tsconfig.json
  client/tsconfig.webpack.json
  client/webpack.config.ts
Labels: enhancement

#219 adding client CD script
  .github/workflows/CD - Client.yml
Labels: enhancement

#224 Use auto-generated thumbnail from azure media service
  api/src/app.ts
  api/src/controllers/VideoController.ts
  api/src/data/MediaClient.ts
  api/src/data/VideoDatabaseClient.ts
  sql-code/sql-functions-and-procedures/video/get_all_video_data.sql
Labels: documentation, enhancement

#232 UI cd
  .github/workflows/CD - Client.yml
Labels: enhancement, github_actions, javascript

#233 Remove Engine
  api/package-lock.json
  api/package.json
Labels: bug

#236 ui upload
  client/src/components/UploadFile/index.tsx
  client/src/pages/UploadPage.tsx
  client/src/types/components/UploadFile.d.ts
  client/src/types/index.d.ts
Labels: enhancement

#237 Axios
  api/src/app.ts
  client/.env.defaults
  client/src/utilities/api.ts
  client/src/utilities/index.ts
  client/src/utilities/paths.tsx
  client/webpack.config.ts
Labels: enhancement

#239 Client Sanity Bug
  client/src/components/App/index.tsx
  client/src/utilities/paths.tsx
Labels: bug

#240 ✨ Added proper redirection for login and logout URL
  api/src/controllers/Auth.ts
Labels: bug, enhancement

#243 Update CD - Client.yml
  .github/workflows/CD - Client.yml
Labels: bug, enhancement

#241 Initial Fix
  api/src/controllers/Auth.ts
  api/src/controllers/VideoController.ts
  client/src/state/data.ts
  client/src/state/sanity.ts
  client/src/state/user.ts
Labels: bug, enhancement

#245 API Axios Fix
  client/src/utilities/api.ts
Labels: bug

#246 add category_names array to each video metadata record
  api/src/data/VideoDatabaseClient.ts
Labels: enhancement

#252 ✨ Upload Form Revamp + Upload API Connectivity
  api/src/controllers/VideoController.ts
  client/src/components/UploadFile/index.tsx
  client/src/pages/UploadPage.tsx
  client/src/state/data.ts
  client/src/types/index.d.ts
  client/src/types/state/Data.d.ts
Labels: bug, enhancement

#254 Navbar Rework
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/components/App/index.tsx
  client/src/components/Navbar/index.tsx
  client/src/index.tsx
  client/src/types/components/Navbar.d.ts
  client/src/utilities/index.ts
  client/src/utilities/paths.tsx
  client/tailwind.config.js
  client/webpack.config.ts
Labels: enhancement

#257 🎨 UI Revamp +⏩ Speed Upgrades
  client/package-lock.json
  client/package.json
  client/src/components/Navbar/index.tsx
  client/src/components/VideoCard/index.tsx
  client/src/pages/VideosPage.tsx
  client/src/utilities/paths.tsx
  client/tailwind.config.js
  client/webpack.config.ts
Labels: bug, enhancement

#275 NPM to yarn
  .github/workflows/CI - API.yml
  .github/workflows/CI - Client.yml
  api/package-lock.json
  api/yarn.lock
  client/package-lock.json
  client/yarn.lock
Labels: dependencies, enhancement

#283 🐛 Fix CD Workflows
  .github/workflows/CD - API.yml
  .github/workflows/CD - Client.yml
Labels: bug

#284 🐛 fix/Fix indentation in CD - Client Workflow
  .github/workflows/CD - Client.yml
Labels: bug, github_actions

#287 🐛 chore/Remove fsevents + ts-jest and use babel
  client/babel.config.js
  client/jest.config.ts
  client/package.json
  client/yarn.lock
Labels: bug, github_actions
